version: 2.1

workflows:
  main:
    jobs:
      - ruby33
      - ruby31
      - ruby32
      - ruby30
      - ruby27
      - ruby26
      - ruby25
      - ruby24

executors:
  ruby33:
    docker:
      - image: cimg/ruby:3.3
      - image: cimg/redis:7.2
  ruby32:
    docker:
      - image: cimg/ruby:3.2
      - image: cimg/redis:7.2
  ruby31:
    docker:
      - image: cimg/ruby:3.1
      - image: cimg/redis:7.2
  ruby30:
    docker:
      - image: cimg/ruby:3.0
      - image: cimg/redis:7.2
  ruby27:
    docker:
      - image: cimg/ruby:2.7
      - image: cimg/redis:7.2
  ruby26:
    docker:
      - image: cimg/ruby:2.7
      - image: cimg/redis:7.2
  ruby25:
    docker:
      - image: cimg/ruby:2.7
      - image: cimg/redis:7.2
  ruby24:
    docker:
      - image: cimg/ruby:2.4
      - image: cimg/redis:7.2

commands:
  test:
    steps:
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install

      - run:
          name: Run rspec
          command: |
            bundle exec rspec --format documentation --format RspecJunitFormatter --out test_results/rspec.xml

jobs:
  ruby33:
    executor: ruby33
    steps:
      - checkout
      - test

      - run:
          name: Report Test Coverage
          command: |
            wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O cc-test-reporter
            chmod +x cc-test-reporter
            ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.json coverage/.resultset.json
            ./cc-test-reporter upload-coverage -i coverage/codeclimate.json

      - store_test_results:
          path: test_results

  ruby32:
    executor: ruby30
    steps:
      - checkout
      - test

  ruby31:
    executor: ruby30
    steps:
      - checkout
      - test

  ruby30:
    executor: ruby30
    steps:
      - checkout
      - test

  ruby27:
    executor: ruby27
    steps:
      - checkout
      - test

  ruby26:
    executor: ruby27
    steps:
      - checkout
      - test

  ruby25:
    executor: ruby27
    steps:
      - checkout
      - test

  ruby24:
    executor: ruby24
    steps:
      - checkout
      - test
